# Generated by Django 4.2.6 on 2024-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null='')),
                ('mobile', models.CharField(blank=True, max_length=225, null='')),
                ('password', models.CharField(blank=True, max_length=225, null='')),
                ('whatsapp', models.CharField(blank=True, max_length=225, null='')),
                ('join', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
