# Generated by Django 4.2.6 on 2024-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_howplaygame'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SingleDigit', models.CharField(blank=True, max_length=225, null='')),
                ('Jodi', models.CharField(blank=True, max_length=225, null='')),
                ('SinglePanna', models.CharField(blank=True, max_length=225, null='')),
                ('DoublePanna', models.CharField(blank=True, max_length=225, null='')),
                ('TripplePanna', models.CharField(blank=True, max_length=225, null='')),
                ('HalfSangam', models.CharField(blank=True, max_length=225, null='')),
                ('FullSangam', models.CharField(blank=True, max_length=225, null='')),
            ],
        ),
    ]
