# Generated by Django 4.2.6 on 2024-08-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminInfo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
