# Generated by Django 4.2.6 on 2024-08-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_delete_admininfo_remove_customer_user_delete_games_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=225, null='')),
                ('telegram', models.CharField(blank=True, max_length=225, null='')),
                ('support', models.CharField(blank=True, max_length=225, null='')),
                ('upi', models.CharField(blank=True, max_length=225, null='')),
                ('barcode', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null='')),
                ('open', models.CharField(blank=True, max_length=225, null='')),
                ('close', models.CharField(blank=True, max_length=225, null='')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytm', models.CharField(blank=True, max_length=225, null='')),
                ('phonepay', models.CharField(blank=True, max_length=225, null='')),
                ('gpay', models.CharField(blank=True, max_length=225, null='')),
                ('ac', models.CharField(blank=True, max_length=255, null='')),
                ('ifsc', models.CharField(blank=True, max_length=225, null='')),
                ('bankname', models.CharField(blank=True, max_length=255, null='')),
                ('holder', models.CharField(blank=True, max_length=255, null='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=125)),
                ('email', models.CharField(blank=True, max_length=225, null='')),
                ('wallet', models.CharField(default=0, max_length=125)),
                ('join', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
