# Generated by Django 4.2.6 on 2024-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(blank=True, max_length=225, null=''),
        ),
    ]
