# Generated by Django 4.2.6 on 2024-08-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_withdrawal_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='on', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='join',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='join',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
