# Generated by Django 4.2.6 on 2024-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_applicationmode_alter_customer_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='status',
            field=models.CharField(blank=True, default='close', max_length=225, null=''),
        ),
    ]
