# Generated by Django 4.2.6 on 2024-09-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_games_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beting',
            name='join',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
