# Generated by Django 4.2.6 on 2024-09-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_beting_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='beting',
            name='gmid',
            field=models.CharField(blank=True, max_length=255, null=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(blank=True, null=''),
        ),
    ]
