# Generated by Django 4.2.6 on 2024-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_beting_gmid_alter_customer_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beting',
            name='gmid',
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.IntegerField(default=0, max_length=125),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(blank=True, max_length=225, null=''),
        ),
    ]
