# Generated by Django 4.2.6 on 2024-09-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_beting_gmid_alter_customer_wallet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beting',
        ),
    ]
