# Generated by Django 4.2.6 on 2024-09-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_depositrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaliDesawarBeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=225, null='')),
                ('name', models.CharField(blank=True, max_length=225, null='')),
                ('pana', models.CharField(blank=True, max_length=225, null='')),
                ('digit', models.CharField(blank=True, max_length=225, null='')),
                ('points', models.CharField(blank=True, max_length=225, null='')),
                ('gametype', models.CharField(blank=True, max_length=225, null='')),
                ('status', models.CharField(blank=True, max_length=225, null='')),
                ('date', models.DateField(auto_now_add=True)),
                ('join', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaliDesawarGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null='')),
                ('open', models.CharField(blank=True, max_length=225, null='')),
                ('close', models.CharField(blank=True, max_length=225, null='')),
                ('chart', models.CharField(blank=True, max_length=225, null='')),
                ('ResultTime', models.CharField(blank=True, max_length=225, null='')),
                ('ClosePanna', models.CharField(blank=True, max_length=225, null='')),
                ('OpenPanna', models.CharField(blank=True, max_length=225, null='')),
                ('status', models.CharField(blank=True, default='close', max_length=225, null='')),
            ],
        ),
        migrations.CreateModel(
            name='StarlineBeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=225, null='')),
                ('name', models.CharField(blank=True, max_length=225, null='')),
                ('pana', models.CharField(blank=True, max_length=225, null='')),
                ('digit', models.CharField(blank=True, max_length=225, null='')),
                ('points', models.CharField(blank=True, max_length=225, null='')),
                ('gametype', models.CharField(blank=True, max_length=225, null='')),
                ('status', models.CharField(blank=True, max_length=225, null='')),
                ('date', models.DateField(auto_now_add=True)),
                ('join', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='starlinegames',
            name='digit',
            field=models.IntegerField(blank=True, default=1, null=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='amount',
            field=models.IntegerField(blank=True, null=''),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(blank=True, null=''),
        ),
    ]
