# Generated by Django 4.2.6 on 2024-09-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_galidesawarbeting_galidesawargame_starlinebeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galidesawargame',
            name='holiday',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='games',
            name='holiday',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='starlinegames',
            name='holiday',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
    ]
