# Generated by Django 4.2.6 on 2024-09-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_beting_bettingid_alter_starlinegames_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='galidesawarbeting',
            name='bettingid',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='starlinebeting',
            name='bettingid',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
    ]
