# Generated by Django 4.2.6 on 2024-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_resulttime_galidesawargame_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='MinimumDeposit',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='MinimumWithdraw',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='WithdrawCloseTime',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='WithdrawOpenTime',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
    ]
