# Generated by Django 4.2.6 on 2024-09-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_admininfo_minimumdeposit_admininfo_minimumwithdraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='bonus',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
    ]
