# Generated by Django 4.2.6 on 2024-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_paymentdetails_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='txid',
            field=models.IntegerField(blank=True, default=1, null=''),
            preserve_default=False,
        ),
    ]
