# Generated by Django 4.2.6 on 2024-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_galidesawarbeting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beting',
            name='date',
        ),
        migrations.AlterField(
            model_name='beting',
            name='join',
            field=models.DateField(blank=True),
        ),
    ]
