# Generated by Django 4.2.6 on 2024-09-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_beting_date_alter_beting_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='beting',
            name='WinAmount',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='galidesawarbeting',
            name='WinAmount',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
        migrations.AddField(
            model_name='starlinebeting',
            name='WinAmount',
            field=models.CharField(blank=True, max_length=225, null=''),
        ),
    ]
